#!/bin/bash

git status

echo -n "Yes or no: "
read choice

function upd {
    ln -sfnv $1 $2x
}

if echo "$choice" | grep -iq "^y" ; then

    upd ~/.extend.Xresources  ./Xresources/.extend.Xresources
    upd ~/.Xresources  ./Xresources/.Xresources 
    upd ~/.config/i3/ ./i3config/
    upd ~/.config/ranger/ ./rangerconfig/
    upd ~/.config/polybar/ ./polybarconfig/

    git add .

    echo -n "Commit msg: "
    read commit_str
    git commit -m "$commit_str"
    
    exit 0
else
    echo "nil"
    exit 2
fi
