#!/bin/bash

alias upd="ln -sfn "

git status

echo -n "Yes or no: "
read commit_str

if echo "$commit_str" | grep -iq "^y" ; then

    upd ~/.extend.Xresources  ./Xresources/.extend.Xresources
    udp ~/.Xresources  ./Xresources/.Xresources
    upd ~/.config/i3/ ./i3config/
    upd ~/.config/ranger/ ./rangerconfig/
    upd ~/.config/polybar/ ./polybarconfig/

    git add .
    git commit -m "$commit_str"
    
    exit 0
else
    exit 2
fi
